reminder_list/urls.py
from django.conf.urls import url

from . import views

app_name = 'reminder_list'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^delete/(?P<question_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^clear$', views.clear, name='clear'),
    url(r'^edit/(?P<action>[a-z0-9]+)/$', views.edit, name='edit'),
    url(r'^successful_add$', views.successful_add, name='successful_add'),
    url(r'reminder_api', views.reminder_api, name='reminder api'),
]

remindersite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('reminder_list.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

reminder_list/models.py
from django.db import models


class Reminder(models.Model):
    title = models.CharField(max_length=200)
    reminder_time = models.DateTimeField('time to remind')
    description = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.title

reminder_list/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reminder
from .widgets import DateTimeInput


class ReminderForm(ModelForm):
    class Meta:
        model = Reminder
        fields = ['title', 'reminder_time', 'description']

    reminder_time = forms.DateTimeField(widget=DateTimeInput())
    description = forms.CharField(required=False, max_length=500)

reminder_list/views.py
import dateutil.parser
from django.http import HttpResponseRedirect
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status, permissions
from rest_framework.parsers import JSONParser
from django.urls import reverse
from django.shortcuts import render
from .models import Reminder
from .serializers import ReminderSerializer
from .forms import ReminderForm


# View for the index of the website, displays the index template
def index(request):
    reminders = Reminder.objects.all().order_by('reminder_time')
    return render(request, 'reminder_list/index.html', {'reminders': reminders})


# View to add a new reminder, displays the add_reminder template
def edit(request, action):
    if action == 'new':
        form = ReminderForm()
        pk = -1
    else:
        form = ReminderForm(instance=Reminder.objects.get(pk=action))
        pk = action
    return render(request, 'reminder_list/add_reminder.html', {'form': form, 'pk': pk})


# View for creating a new reminder, receives info from add_reminder template and adds a new entry to the DB
def successful_add(request):
    pk = int(request.POST['pk'])
    if pk > 0:
        reminder = Reminder.objects.get(pk=pk)
        reminder.title = request.POST['title']
        reminder.description = request.POST['description']
        reminder.reminder_time = dateutil.parser.parse(request.POST['reminder_time'])
        reminder.save()
    else:
        new_reminder = Reminder(title=request.POST['title'],
                                description=request.POST['description'],
                                reminder_time=dateutil.parser.parse(
                                    request.POST['reminder_time']))
        new_reminder.save()
    return HttpResponseRedirect(reverse('reminder_list:index'))


def detail(request, question_id):
    reminder = Reminder.objects.get(pk=question_id)
    return render(request, 'reminder_list/detail.html', {'reminder': reminder,
                                                         'pk': question_id})


def delete(request, question_id):
    reminder = Reminder.objects.get(pk=question_id)
    reminder.delete()
    return HttpResponseRedirect(reverse('reminder_list:index'))


# TODO add support for editing existing reminders
@api_view(['GET', 'POST'])
@permission_classes((permissions.AllowAny,))
def reminder_api(request):
    """
    List all reminders, or create a new reminder
    """
    if request.method == 'GET':
        reminders = Reminder.objects.all()
        serializer = ReminderSerializer(reminders, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ReminderSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def clear(request):
    Reminder.objects.all().delete()
    return HttpResponseRedirect(reverse('reminder_list:index'))

reminder_list/templates/reminder_list/add_reminder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <form action="{% url 'reminder_list:successful_add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" value="{{ pk }}" name="pk"/>
        <input type="submit" value="Add Reminder"/>
    </form>
</body>
</html>

reminder_list/templates/reminder_list/detail.html
<html>
    <head>
        <title>Detail</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <h1>{{ reminder.title }}</h1>
        <h2>{{ reminder.description }}</h2>
        <p>{{ reminder.reminder_time }}</p>
        <a href="/delete/{{ reminder.pk }}">Delete</a>
        <a href="/edit/{{ reminder.pk }}">Edit</a>
    </body>
</html>

reminder_list/templates/reminder_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    {# displays all reminders present#}
    {% for x in reminders %}
    <h1><a href="{{ x.pk }}">{{ x.title }}</a></h1>
    <h2>{{ x.reminder_time }}</h2>
    {% endfor %}
    {# link to create a new reminder#}
    <a href="/edit/new">Add Reminder</a>
</body>
</html>